name: Continuos Integration

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements/dev.txt"

      - name: Install Python dependencies
        run: pip install -r requirements/dev.txt

      - name: Generate documentation
        run: |
          sphinx-apidoc -M -P -o docs/modules example
          sphinx-build -v -n docs public

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: public
